- hosts: all
  gather_facts: no
  tasks:
  - name: Update cache
    apt: update_cache=yes
    become: yes
  - name: Install packages
    apt: name={{item}}
    with_items:
      - postgresql
      - python-psycopg2
      - default-jre
      - default-jdk
      - maven
    become: yes

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no
  vars:
    dbname: music_cloud
    dbuser: viktor_kulygin
    dbpassword: 123456
    port: 5432
  tasks:
  - name: Copy Postgres config (1 / 2)
    copy: src=/vagrant/cm/postgresql_configuration/postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf owner=postgres group=postgres
    become: yes
  - name: Copy Postgres config (2 / 2)
    copy: src=/vagrant/cm/postgresql_configuration/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres
    become: yes
  - name: Restart Postgres service
    service: name=postgresql state=restarted
  - name: Drop database
    postgresql_db: name={{dbname}} port={{port}} state=absent
    become: yes
  - name: Create database
    postgresql_db: name={{dbname}} port={{port}}
    become: yes
  - name: Ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL port={{port}}
#  - name: Ensure user does not have unnecessary privilege
#    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  - name: Set psql user as usperuser
    postgresql_user: name={{dbuser}} role_attr_flags=SUPERUSER port={{port}}
  - name: Restart Postgres service
    service: name=postgresql state=restarted
    become: yes
  - name: Build database schema
    shell: "psql -d {{dbname}} -a -f /vagrant/DataBaseScheme/database_scheme.sql"
    become: yes
  - name: Database add test data 
    shell: "psql -d {{dbname}} -a -f /vagrant/DataBaseScheme/database_data.sql"
    become: yes
  - name: Start Postgresql on boot
    shell: "update-rc.d postgresql defaults"
    become: yes

- hosts: all
  user: root
  tasks:
  - name: Add Tomcat user
    user: name=tomcat
    become: yes
  - name: Download Tomcat
    get_url: url=http://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-8/v8.5.4/bin/apache-tomcat-8.5.4.tar.gz dest=/opt
    become: yes
  - name: Extract Tomcat archive
    shell: tar xf /opt/apache-tomcat-8.5.4.tar.gz -C /opt
    become: yes
  - name: Create /opt/tomcat symlink
    file: src=/opt/apache-tomcat-8.5.4 dest=/opt/tomcat owner=tomcat
     state=link
    become: yes
  - name: Delete directory music-cloud
    shell: "rm -R -f /opt/tomcat/webapps/music-cloud"
    become: yes
  - name: Delete old music_cloud.war
    shell: "rm -f /opt/tomcat/webapps/music-cloud.war"
    become: yes
  - name: Application packaging
    shell: mvn package
    become: yes
  - name: Deploy music-cloud.war		
    copy: src=/vagrant/target/music-cloud.war dest=/opt/apache-tomcat-8.5.4/webapps/music-cloud.war owner=tomcat group=tomcat		
    become: yes
  - name: Start Tomcat
    shell: /opt/tomcat/bin/startup.sh
    become: yes
